export type VocabItem = {
  word: string;
  translation: string;
};

export const TOEIC_WORDS: VocabItem[] = [
  // --- Business / Management ---
  { word: "accommodate", translation: "収容する・対応する" },
  { word: "accomplish", translation: "達成する・成し遂げる" },
  { word: "adjacent", translation: "隣接した・すぐ近くの" },
  { word: "agenda", translation: "議題・会議の予定表" },
  { word: "allocate", translation: "割り当てる・配分する" },
  { word: "anticipate", translation: "予期する・見越す" },
  { word: "apparent", translation: "明らかな・見た目の" },
  { word: "approval", translation: "承認・賛成" },
  { word: "assess", translation: "評価する・査定する" },
  { word: "assign", translation: "割り当てる・任命する" },
  { word: "assist", translation: "助ける・支援する" },
  { word: "authorize", translation: "認可する・権限を与える" },
  { word: "beneficial", translation: "有益な・利益をもたらす" },
  { word: "capacity", translation: "容量・収容能力・能力" },
  { word: "clarify", translation: "明確にする・説明する" },
  { word: "compensate", translation: "補償する・埋め合わせる" },
  { word: "compile", translation: "編集する・まとめる" },
  { word: "confirm", translation: "確認する・確かめる" },
  { word: "consecutive", translation: "連続した・立て続けの" },
  { word: "considerable", translation: "かなりの・相当な" },
  { word: "coordinate", translation: "調整する・連携する" },
  { word: "dedicated", translation: "専用の・献身的な" },
  { word: "delegate", translation: "委任する・代表者" },
  { word: "demonstrate", translation: "実演する・証明する" },
  { word: "designate", translation: "指定する・任命する" },
  { word: "distribute", translation: "配布する・分配する" },
  { word: "eligible", translation: "資格のある・適格な" },
  { word: "eliminate", translation: "取り除く・除外する" },
  { word: "emphasize", translation: "強調する・重点を置く" },
  { word: "enhance", translation: "強化する・高める" },
  { word: "ensure", translation: "確実にする・保証する" },
  { word: "establish", translation: "設立する・確立する" },
  { word: "evaluate", translation: "評価する・査定する" },
  { word: "exceed", translation: "超える・上回る" },
  { word: "execute", translation: "実行する・遂行する" },
  { word: "facilitate", translation: "促進する・容易にする" },
  { word: "flexible", translation: "柔軟な・融通のきく" },
  { word: "generate", translation: "生み出す・発生させる" },
  { word: "implement", translation: "実施する・実装する" },
  { word: "initiative", translation: "主導権・新しい取り組み" },
  { word: "inspect", translation: "検査する・点検する" },
  { word: "integrate", translation: "統合する・まとめる" },
  { word: "monitor", translation: "監視する・モニタリングする" },
  { word: "negotiate", translation: "交渉する・折衝する" },
  { word: "obtain", translation: "得る・取得する" },
  { word: "optimize", translation: "最適化する・最大限に活用する" },
  { word: "participate", translation: "参加する・加わる" },
  { word: "prioritize", translation: "優先順位をつける" },
  { word: "procedure", translation: "手順・手続き" },
  { word: "promote", translation: "促進する・昇進させる" },
  { word: "qualify", translation: "資格を得る・適格である" },
  { word: "recommend", translation: "推薦する・勧める" },
  { word: "regulate", translation: "規制する・調整する" },
  { word: "resolve", translation: "解決する・決意する" },
  { word: "responsibility", translation: "責任・義務" },
  { word: "retain", translation: "保持する・維持する" },
  { word: "revise", translation: "改訂する・修正する" },
  { word: "submit", translation: "提出する・申請する" },
  { word: "supervise", translation: "監督する・管理する" },
  { word: "survey", translation: "調査する・アンケート" },
  { word: "transfer", translation: "転送する・移転する" },
  { word: "upgrade", translation: "改善する・アップグレードする" },
  { word: "verify", translation: "確認する・立証する" },
  { word: "efficient", translation: "効率的な・能率のよい" },
  { word: "productive", translation: "生産的な・実りある" },
  { word: "mandatory", translation: "義務的な・必須の" },
  { word: "preliminary", translation: "予備の・準備段階の" },
  { word: "comprehensive", translation: "包括的な・総合的な" },
  { word: "strategic", translation: "戦略的な・重要な" },
  { word: "competent", translation: "有能な・能力のある" },
  { word: "diversify", translation: "多様化する・多角化する" },
  { word: "restructure", translation: "再構築する・組織改革する" },
  { word: "collaborate", translation: "協力する・共同作業する" },
  { word: "outsource", translation: "外部委託する" },
  { word: "streamline", translation: "合理化する・効率化する" },
  { word: "launch", translation: "立ち上げる・発売する" },
  { word: "boost", translation: "増やす・後押しする" },
  { word: "brief", translation: "簡単に説明する・概要を伝える" },
  { word: "substantial", translation: "かなりの・実質的な" },
  { word: "personnel", translation: "人員・職員・人事" },
  { word: "inquiry", translation: "問い合わせ・調査" },
  { word: "correspondence", translation: "連絡・文通・書簡" },
  { word: "feasible", translation: "実行可能な・実現できる" },
  { word: "initiative", translation: "主導権・率先した取り組み" },
  { word: "benchmark", translation: "基準・指標" },
  { word: "compliance", translation: "法令遵守・従うこと" },
  { word: "procurement", translation: "調達・取得" },
  { word: "turnaround", translation: "好転・方向転換・処理時間" },
  { word: "incentive", translation: "奨励・動機・インセンティブ" },
  { word: "affiliate", translation: "関連会社・提携する" },
  { word: "subsidiary", translation: "子会社・補助的な" },
  { word: "merger", translation: "合併・企業統合" },
  { word: "acquisition", translation: "買収・取得" },
  { word: "benchmark", translation: "基準・水準" },
  { word: "downturn", translation: "景気後退・低迷" },
  { word: "overhead", translation: "経費・諸経費・上部の" },
  { word: "delegate", translation: "代表者・委任する" },

  // --- Finance / Economics ---
  { word: "budget", translation: "予算・予算を立てる" },
  { word: "capital", translation: "資本・元手・首都" },
  { word: "commission", translation: "手数料・委託する・委員会" },
  { word: "deficit", translation: "赤字・不足額" },
  { word: "dividend", translation: "配当・利益配分" },
  { word: "expenditure", translation: "支出・経費" },
  { word: "fiscal", translation: "財政の・会計年度の" },
  { word: "forecast", translation: "予測する・予報" },
  { word: "inflation", translation: "インフレ・物価上昇" },
  { word: "invoice", translation: "請求書・インボイス" },
  { word: "liability", translation: "負債・責任・リスク" },
  { word: "monetary", translation: "金融の・貨幣の" },
  { word: "quarterly", translation: "四半期ごとの・季刊の" },
  { word: "reimburse", translation: "払い戻す・弁済する" },
  { word: "revenue", translation: "収入・歳入・売上高" },
  { word: "shareholder", translation: "株主" },
  { word: "subsidy", translation: "補助金・助成金" },
  { word: "surplus", translation: "余剰・黒字・過剰" },
  { word: "transaction", translation: "取引・処理" },
  { word: "withdraw", translation: "引き出す・撤退する" },
  { word: "audit", translation: "監査する・会計検査" },
  { word: "equity", translation: "株主資本・公平性" },
  { word: "liquidity", translation: "流動性・現金化のしやすさ" },
  { word: "portfolio", translation: "ポートフォリオ・投資一覧" },
  { word: "premium", translation: "プレミアム・保険料・割増金" },
  { word: "recession", translation: "景気後退・不況" },
  { word: "cash flow", translation: "キャッシュフロー・資金の流れ" },
  { word: "interest rate", translation: "金利・利率" },
  { word: "profit margin", translation: "利益率・利幅" },
  { word: "break even", translation: "損益分岐点に達する" },
  { word: "gross profit", translation: "粗利益・売上総利益" },
  { word: "net income", translation: "純利益・税引き後利益" },
  { word: "payroll", translation: "給与計算・給与支払い" },
  { word: "depreciation", translation: "減価償却・価値の低下" },
  { word: "collateral", translation: "担保・副次的な" },
  { word: "deductible", translation: "控除できる・免責額" },
  { word: "appraise", translation: "査定する・評価する" },
  { word: "amortize", translation: "償却する・分割払いする" },
  { word: "hedge", translation: "リスクを回避する・ヘッジ" },
  { word: "fiscal year", translation: "会計年度" },
  { word: "outstanding", translation: "未払いの・傑出した" },
  { word: "quote", translation: "見積もり・引用する" },
  { word: "venture capital", translation: "ベンチャーキャピタル・創業支援資金" },
  { word: "stock option", translation: "ストックオプション・株式購入権" },
  { word: "balance sheet", translation: "貸借対照表・バランスシート" },

  // --- Legal / Contracts ---
  { word: "agreement", translation: "合意・契約・同意" },
  { word: "arbitration", translation: "仲裁・調停" },
  { word: "binding", translation: "拘束力のある・義務的な" },
  { word: "breach", translation: "違反・違約・破る" },
  { word: "clause", translation: "条項・節・句" },
  { word: "comply", translation: "従う・応じる" },
  { word: "confidential", translation: "秘密の・機密扱いの" },
  { word: "consent", translation: "同意・承諾する" },
  { word: "copyright", translation: "著作権・版権" },
  { word: "dispute", translation: "紛争・異議を唱える" },
  { word: "enforce", translation: "施行する・強制する" },
  { word: "expire", translation: "期限切れになる・満了する" },
  { word: "liable", translation: "責任がある・義務を負う" },
  { word: "obligation", translation: "義務・責務" },
  { word: "patent", translation: "特許・特許を取る" },
  { word: "penalty", translation: "罰則・ペナルティ" },
  { word: "provision", translation: "条項・規定・準備" },
  { word: "terminate", translation: "終了する・解雇する" },
  { word: "trademark", translation: "商標・トレードマーク" },
  { word: "warranty", translation: "保証・保証書" },
  { word: "indemnify", translation: "補償する・免責する" },
  { word: "jurisdiction", translation: "管轄・司法権" },
  { word: "waive", translation: "放棄する・免除する" },
  { word: "deed", translation: "証書・行為" },
  { word: "litigation", translation: "訴訟・係争" },
  { word: "sanction", translation: "制裁・許可する" },
  { word: "subcontract", translation: "下請けに出す・下請け契約" },
  { word: "disclosure", translation: "開示・公表" },
  { word: "proprietary", translation: "専有の・独占的な" },
  { word: "non-disclosure", translation: "非開示・秘密保持" },

  // --- Technology ---
  { word: "bandwidth", translation: "帯域幅・通信速度" },
  { word: "compatible", translation: "互換性のある・共存できる" },
  { word: "configure", translation: "設定する・構成する" },
  { word: "database", translation: "データベース" },
  { word: "debug", translation: "デバッグする・バグを修正する" },
  { word: "deploy", translation: "導入する・展開する" },
  { word: "encrypt", translation: "暗号化する" },
  { word: "firewall", translation: "ファイアウォール・防火壁" },
  { word: "infrastructure", translation: "インフラ・基盤" },
  { word: "interface", translation: "インターフェース・接点" },
  { word: "malfunction", translation: "誤作動する・不具合" },
  { word: "protocol", translation: "プロトコル・手順・礼儀" },
  { word: "synchronize", translation: "同期する・タイミングを合わせる" },
  { word: "user-friendly", translation: "使いやすい・わかりやすい" },
  { word: "virtual", translation: "仮想の・事実上の" },
  { word: "wireless", translation: "無線の・ワイヤレス" },
  { word: "algorithm", translation: "アルゴリズム・計算手順" },
  { word: "automation", translation: "自動化・オートメーション" },
  { word: "cybersecurity", translation: "サイバーセキュリティ" },
  { word: "cloud computing", translation: "クラウドコンピューティング" },
  { word: "scalable", translation: "拡張性のある・スケーラブルな" },
  { word: "firmware", translation: "ファームウェア" },
  { word: "latency", translation: "遅延・待ち時間" },
  { word: "redundancy", translation: "冗長性・余分なバックアップ" },
  { word: "troubleshoot", translation: "トラブルシューティングする・問題を解決する" },
  { word: "migration", translation: "移行・データ移行" },
  { word: "repository", translation: "リポジトリ・貯蔵所" },
  { word: "authentication", translation: "認証・本人確認" },
  { word: "backup", translation: "バックアップする・予備の" },
  { word: "patch", translation: "パッチを当てる・修正する" },
  { word: "specification", translation: "仕様・スペック" },
  { word: "integration", translation: "統合・連携" },
  { word: "downtime", translation: "停止時間・ダウンタイム" },
  { word: "bandwidth", translation: "帯域幅・通信容量" },
  { word: "proxy", translation: "代理・プロキシ" },

  // --- Travel / Transport ---
  { word: "accommodation", translation: "宿泊施設・宿泊場所" },
  { word: "boarding", translation: "搭乗・乗り込み" },
  { word: "carry-on", translation: "機内持ち込み荷物" },
  { word: "check-in", translation: "チェックイン・搭乗手続き" },
  { word: "commute", translation: "通勤する・通勤" },
  { word: "depart", translation: "出発する・旅立つ" },
  { word: "destination", translation: "目的地・行き先" },
  { word: "domestic", translation: "国内の・家庭の" },
  { word: "fare", translation: "運賃・料金" },
  { word: "itinerary", translation: "旅程・旅行計画" },
  { word: "layover", translation: "乗り継ぎ待ち・途中停車" },
  { word: "overseas", translation: "海外の・外国への" },
  { word: "refund", translation: "払い戻し・返金する" },
  { word: "reservation", translation: "予約・保留" },
  { word: "round trip", translation: "往復・往復旅行" },
  { word: "terminal", translation: "ターミナル・端末・最終の" },
  { word: "transit", translation: "乗り継ぎ・通過" },
  { word: "visa", translation: "ビザ・査証" },
  { word: "customs", translation: "税関・習慣" },
  { word: "express", translation: "急行・速達・表現する" },
  { word: "charter", translation: "チャーターする・特別便" },
  { word: "currency exchange", translation: "両替・外国為替" },
  { word: "baggage claim", translation: "手荷物受取所" },
  { word: "connecting flight", translation: "乗り継ぎ便" },
  { word: "excess baggage", translation: "超過手荷物" },
  { word: "shuttle", translation: "シャトル・往復便" },
  { word: "boarding pass", translation: "搭乗券" },
  { word: "departure lounge", translation: "出発ラウンジ" },
  { word: "complimentary", translation: "無料の・お世辞の" },
  { word: "amenity", translation: "アメニティ・設備・快適さ" },

  // --- Medical / Health ---
  { word: "allergy", translation: "アレルギー・過敏症" },
  { word: "appointment", translation: "予約・約束・任命" },
  { word: "chronic", translation: "慢性的な・長期の" },
  { word: "diagnosis", translation: "診断・見立て" },
  { word: "fatigue", translation: "疲労・消耗" },
  { word: "medication", translation: "薬・投薬治療" },
  { word: "nutrition", translation: "栄養・栄養摂取" },
  { word: "outpatient", translation: "外来患者・通院患者" },
  { word: "prescription", translation: "処方箋・処方" },
  { word: "prevention", translation: "予防・防止" },
  { word: "recovery", translation: "回復・復旧" },
  { word: "rehabilitation", translation: "リハビリ・社会復帰" },
  { word: "specialist", translation: "専門医・専門家" },
  { word: "symptom", translation: "症状・徴候" },
  { word: "therapy", translation: "療法・治療" },
  { word: "vaccination", translation: "ワクチン接種・予防接種" },
  { word: "wellness", translation: "健康・良好な状態" },
  { word: "pharmacy", translation: "薬局・調剤薬局" },
  { word: "adverse effect", translation: "副作用・悪影響" },
  { word: "dosage", translation: "投与量・用量" },
  { word: "clinical trial", translation: "臨床試験" },
  { word: "contagious", translation: "伝染性の・感染する" },
  { word: "immune", translation: "免疫のある・影響を受けない" },
  { word: "inflammation", translation: "炎症・腫れ" },
  { word: "physician", translation: "内科医・医師" },
  { word: "remedy", translation: "治療薬・改善策" },
  { word: "supplement", translation: "サプリメント・補足する" },
  { word: "chronic", translation: "慢性的な・長続きする" },

  // --- General / Academic ---
  { word: "adapt", translation: "適応する・変える" },
  { word: "adequate", translation: "十分な・適切な" },
  { word: "alternative", translation: "代替の・選択肢" },
  { word: "approximate", translation: "おおよその・近似の" },
  { word: "cite", translation: "引用する・例として挙げる" },
  { word: "conclude", translation: "結論づける・終わらせる" },
  { word: "consistent", translation: "一貫した・矛盾のない" },
  { word: "contrast", translation: "対比する・対照" },
  { word: "controversial", translation: "論争的な・物議を醸す" },
  { word: "convert", translation: "変換する・改宗する" },
  { word: "cooperate", translation: "協力する・協働する" },
  { word: "decline", translation: "断る・低下する・衰退" },
  { word: "diverse", translation: "多様な・さまざまな" },
  { word: "examine", translation: "調べる・診察する" },
  { word: "expand", translation: "拡大する・広げる" },
  { word: "expertise", translation: "専門知識・熟練" },
  { word: "fundamental", translation: "基本的な・根本的な" },
  { word: "highlight", translation: "強調する・主要な点" },
  { word: "hypothesis", translation: "仮説・仮定" },
  { word: "identify", translation: "識別する・特定する" },
  { word: "impact", translation: "影響・衝撃・影響を与える" },
  { word: "indicate", translation: "示す・指摘する" },
  { word: "individual", translation: "個人の・個別の" },
  { word: "influence", translation: "影響する・影響力" },
  { word: "interpret", translation: "解釈する・通訳する" },
  { word: "justify", translation: "正当化する・理由を示す" },
  { word: "maintain", translation: "維持する・主張する" },
  { word: "majority", translation: "大多数・過半数" },
  { word: "moderate", translation: "適度な・穏やかな・司会する" },
  { word: "numerous", translation: "多数の・非常に多い" },
  { word: "objective", translation: "客観的な・目標・目的" },
  { word: "overall", translation: "全体的な・概して" },
  { word: "pattern", translation: "パターン・模様・傾向" },
  { word: "perspective", translation: "観点・見方・視点" },
  { word: "potential", translation: "潜在的な・可能性" },
  { word: "primarily", translation: "主に・まず第一に" },
  { word: "principle", translation: "原則・原理・主義" },
  { word: "propose", translation: "提案する・申し出る" },
  { word: "rationale", translation: "根拠・論理的な説明" },
  { word: "recognize", translation: "認識する・認める" },
  { word: "relevant", translation: "関連性のある・適切な" },
  { word: "reliable", translation: "信頼できる・頼りになる" },
  { word: "reveal", translation: "明らかにする・暴露する" },
  { word: "significant", translation: "重要な・意義深い・かなりの" },
  { word: "specific", translation: "特定の・具体的な" },
  { word: "sufficient", translation: "十分な・足りている" },
  { word: "typically", translation: "通常・一般的に" },
  { word: "widespread", translation: "広範囲にわたる・普及した" },
  { word: "acknowledge", translation: "認める・承認する" },
  { word: "anticipate", translation: "予期する・見越す" },
  { word: "assume", translation: "思い込む・引き受ける" },
  { word: "clarify", translation: "明確にする・はっきりさせる" },
  { word: "comprehensive", translation: "包括的な・総合的な" },
  { word: "construct", translation: "建設する・構築する" },
  { word: "context", translation: "文脈・状況・背景" },
  { word: "contribute", translation: "貢献する・寄付する" },
  { word: "criticize", translation: "批判する・批評する" },
  { word: "distinguish", translation: "区別する・識別する" },
  { word: "elaborate", translation: "詳細に説明する・念入りな" },
  { word: "emerge", translation: "現れる・明らかになる" },
  { word: "encounter", translation: "遭遇する・出会い" },
  { word: "framework", translation: "枠組み・フレームワーク" },
  { word: "implication", translation: "意味合い・影響・示唆" },
  { word: "incorporate", translation: "取り入れる・組み込む" },
  { word: "inherent", translation: "固有の・本来備わった" },
  { word: "investigate", translation: "調査する・捜査する" },
  { word: "mutual", translation: "相互の・共通の" },
  { word: "perceive", translation: "知覚する・理解する" },
  { word: "phenomenon", translation: "現象・事象" },
  { word: "relevant", translation: "関連性のある・適切な" },
  { word: "subordinate", translation: "部下・下位の" },
  { word: "supplement", translation: "補足する・追加する" },
  { word: "trait", translation: "特性・特徴・性質" },
  { word: "undertake", translation: "引き受ける・着手する" },
  { word: "validity", translation: "妥当性・有効性" },
  { word: "via", translation: "〜経由で・〜を通じて" },
  { word: "whereas", translation: "〜である一方・それに対して" },
  { word: "yield", translation: "生み出す・産出する・譲る" },
  { word: "ambiguous", translation: "曖昧な・多義的な" },
  { word: "coherent", translation: "一貫した・筋の通った" },
  { word: "criteria", translation: "基準・判断規準" },
  { word: "explicit", translation: "明示的な・はっきりとした" },
  { word: "implicit", translation: "暗黙の・含意された" },
  { word: "innovative", translation: "革新的な・新しい" },
  { word: "subsequent", translation: "その後の・続く" },
  { word: "sustainable", translation: "持続可能な・維持できる" },
  { word: "transparency", translation: "透明性・わかりやすさ" },
  { word: "unprecedented", translation: "前例のない・空前の" },

  // --- Phrasal verbs / Idioms / Collocations ---
  { word: "account for", translation: "〜を説明する・〜を占める" },
  { word: "ahead of schedule", translation: "予定より早く・前倒しで" },
  { word: "back up", translation: "バックアップする・支持する" },
  { word: "bear in mind", translation: "心に留めておく・覚えておく" },
  { word: "break down", translation: "故障する・分解する・崩れる" },
  { word: "bring about", translation: "引き起こす・もたらす" },
  { word: "bring up", translation: "話題を持ち出す・育てる" },
  { word: "carry out", translation: "実行する・遂行する" },
  { word: "catch up with", translation: "追いつく・近況を知る" },
  { word: "come across", translation: "偶然出会う・印象を与える" },
  { word: "come up with", translation: "思いつく・考え出す" },
  { word: "count on", translation: "頼る・当てにする" },
  { word: "cut back on", translation: "削減する・減らす" },
  { word: "deal with", translation: "対処する・取り組む" },
  { word: "draw up", translation: "作成する・計画を立てる" },
  { word: "find out", translation: "調べる・わかる" },
  { word: "follow up", translation: "フォローアップする・後追いする" },
  { word: "get along with", translation: "うまくやっていく・仲良くする" },
  { word: "give up", translation: "諦める・やめる" },
  { word: "hand in", translation: "提出する・差し出す" },
  { word: "hold off", translation: "延期する・思いとどまる" },
  { word: "in advance", translation: "事前に・前もって" },
  { word: "in charge of", translation: "〜を担当している・〜の責任者" },
  { word: "in terms of", translation: "〜の観点から・〜に関して" },
  { word: "keep track of", translation: "追跡する・把握する" },
  { word: "kick off", translation: "開始する・スタートさせる" },
  { word: "lay off", translation: "解雇する・一時解雇する" },
  { word: "lead to", translation: "〜につながる・引き起こす" },
  { word: "look forward to", translation: "〜を楽しみにする" },
  { word: "look into", translation: "調査する・検討する" },
  { word: "make progress", translation: "進歩する・前進する" },
  { word: "meet the deadline", translation: "締め切りに間に合わせる" },
  { word: "narrow down", translation: "絞り込む・候補を減らす" },
  { word: "on behalf of", translation: "〜を代表して・〜のために" },
  { word: "out of stock", translation: "在庫切れ・品切れ" },
  { word: "pay attention to", translation: "〜に注意を払う" },
  { word: "pick up", translation: "拾う・迎えに行く・上達する" },
  { word: "point out", translation: "指摘する・示す" },
  { word: "put off", translation: "延期する・後回しにする" },
  { word: "reach out", translation: "連絡を取る・手を差し伸べる" },
  { word: "run out of", translation: "〜を使い果たす・なくなる" },
  { word: "set up", translation: "設立する・準備する・仕掛ける" },
  { word: "show up", translation: "現れる・姿を見せる" },
  { word: "sort out", translation: "解決する・整理する" },
  { word: "speed up", translation: "加速する・速める" },
  { word: "stand out", translation: "目立つ・際立つ" },
  { word: "take advantage of", translation: "〜を利用する・〜に乗じる" },
  { word: "take care of", translation: "〜の世話をする・処理する" },
  { word: "take into account", translation: "考慮に入れる・勘案する" },
  { word: "take over", translation: "引き継ぐ・乗っ取る" },
  { word: "team up", translation: "チームを組む・協力する" },
  { word: "touch base", translation: "連絡を取る・情報を共有する" },
  { word: "turn down", translation: "断る・音量を下げる" },
  { word: "turn out", translation: "〜という結果になる・判明する" },
  { word: "up to date", translation: "最新の・現代的な" },
  { word: "work out", translation: "うまくいく・解決する・運動する" },
  { word: "wrap up", translation: "まとめる・終わらせる" },
  { word: "due to", translation: "〜のために・〜が原因で" },
  { word: "regardless of", translation: "〜に関わらず・〜を問わず" },
  { word: "in addition to", translation: "〜に加えて・さらに" },
  { word: "as a result", translation: "その結果・結果として" },
  { word: "on the other hand", translation: "一方では・その反面" },
  { word: "take place", translation: "起こる・行われる" },
  { word: "prior to", translation: "〜の前に・〜に先立って" },
  { word: "in order to", translation: "〜するために" },
  { word: "according to", translation: "〜によれば・〜に従って" },
  { word: "as soon as possible", translation: "できるだけ早く（ASAP）" },
  { word: "at first glance", translation: "一見したところ・ぱっと見" },
  { word: "in the meantime", translation: "その間・それまでの間" },
  { word: "once in a while", translation: "時々・たまに" },
  { word: "needless to say", translation: "言うまでもなく・当然" },
  { word: "fall behind", translation: "遅れる・後退する" },
  { word: "figure out", translation: "理解する・解決する" },
  { word: "get started", translation: "始める・取りかかる" },
  { word: "go ahead", translation: "進める・どうぞ" },
  { word: "go over", translation: "確認する・見直す" },
  { word: "keep up with", translation: "〜についていく・遅れを取らない" },
  { word: "make sure", translation: "確認する・確かめる" },
  { word: "move forward", translation: "前進する・進める" },
  { word: "rule out", translation: "除外する・排除する" },
  { word: "sum up", translation: "要約する・まとめる" },
  { word: "turn around", translation: "好転させる・向きを変える" },
  { word: "walk through", translation: "順を追って説明する・案内する" },
  { word: "cut corners", translation: "手を抜く・近道をする" },
  { word: "get the ball rolling", translation: "物事を動かし始める・始動させる" },
  { word: "hit the ground running", translation: "即戦力として活躍する・飛び出す" },
  { word: "on the same page", translation: "同じ認識を持っている・意見が一致している" },
  { word: "think outside the box", translation: "固定観念にとらわれずに考える" },
  { word: "touch base with", translation: "〜と連絡を取る・情報を確認する" },
  { word: "bring to light", translation: "明らかにする・暴露する" },
  { word: "call it a day", translation: "その日の仕事を終える・今日はここまでにする" },
  { word: "go the extra mile", translation: "余分な努力をする・一歩踏み込む" },
  { word: "in the loop", translation: "情報を共有されている・把握している" },
  { word: "keep in mind", translation: "覚えておく・念頭に置く" },
  { word: "state of the art", translation: "最先端の・最新技術の" },
  { word: "under the circumstances", translation: "状況を考えると・この状況では" },
  { word: "worth while", translation: "価値のある・やりがいのある" },
  { word: "at one's disposal", translation: "自由に使える・利用できる" },
  { word: "with regard to", translation: "〜に関して・〜について" },
  { word: "subject to", translation: "〜に従う・〜次第の" },
  { word: "in light of", translation: "〜を考慮して・〜に照らして" },
];

// ---------------------------------------------------------------------------
// Difficulty helpers
// ---------------------------------------------------------------------------

export type Difficulty = 'easy' | 'medium' | 'hard';

/** Travel/Transport + Phrasal verbs → easy */
const EASY_WORDS = new Set<string>([
  // Travel / Transport
  'accommodation', 'boarding', 'carry-on', 'check-in', 'commute', 'depart',
  'destination', 'domestic', 'fare', 'itinerary', 'layover', 'overseas',
  'refund', 'reservation', 'round trip', 'terminal', 'transit', 'visa',
  'customs', 'express', 'charter', 'currency exchange', 'baggage claim',
  'connecting flight', 'excess baggage', 'shuttle', 'boarding pass',
  'departure lounge', 'complimentary', 'amenity',
  // Phrasal verbs / Idioms / Collocations
  'account for', 'ahead of schedule', 'back up', 'bear in mind', 'break down',
  'bring about', 'bring up', 'carry out', 'catch up with', 'come across',
  'come up with', 'count on', 'cut back on', 'deal with', 'draw up',
  'find out', 'follow up', 'get along with', 'give up', 'hand in',
  'hold off', 'in advance', 'in charge of', 'in terms of', 'keep track of',
  'kick off', 'lay off', 'lead to', 'look forward to', 'look into',
  'make progress', 'meet the deadline', 'narrow down', 'on behalf of',
  'out of stock', 'pay attention to', 'pick up', 'point out', 'put off',
  'reach out', 'run out of', 'set up', 'show up', 'sort out', 'speed up',
  'stand out', 'take advantage of', 'take care of', 'take into account',
  'take over', 'team up', 'touch base', 'turn down', 'turn out', 'up to date',
  'work out', 'wrap up', 'due to', 'regardless of', 'in addition to',
  'as a result', 'on the other hand', 'take place', 'prior to', 'in order to',
  'according to', 'as soon as possible', 'at first glance', 'in the meantime',
  'once in a while', 'needless to say', 'fall behind', 'figure out',
  'get started', 'go ahead', 'go over', 'keep up with', 'make sure',
  'move forward', 'rule out', 'sum up', 'turn around', 'walk through',
  'cut corners', 'get the ball rolling', 'hit the ground running',
  'on the same page', 'think outside the box', 'touch base with',
  'bring to light', 'call it a day', 'go the extra mile', 'in the loop',
  'keep in mind', 'state of the art', 'under the circumstances', 'worth while',
  "at one's disposal", 'with regard to', 'subject to', 'in light of',
]);

/** Finance/Economics + Legal/Contracts → hard */
const HARD_WORDS = new Set<string>([
  // Finance / Economics
  'budget', 'capital', 'commission', 'deficit', 'dividend', 'expenditure',
  'fiscal', 'forecast', 'inflation', 'invoice', 'liability', 'monetary',
  'quarterly', 'reimburse', 'revenue', 'shareholder', 'subsidy', 'surplus',
  'transaction', 'withdraw', 'audit', 'equity', 'liquidity', 'portfolio',
  'premium', 'recession', 'cash flow', 'interest rate', 'profit margin',
  'break even', 'gross profit', 'net income', 'payroll', 'depreciation',
  'collateral', 'deductible', 'appraise', 'amortize', 'hedge', 'fiscal year',
  'outstanding', 'quote', 'venture capital', 'stock option', 'balance sheet',
  // Legal / Contracts
  'agreement', 'arbitration', 'binding', 'breach', 'clause', 'comply',
  'confidential', 'consent', 'copyright', 'dispute', 'enforce', 'expire',
  'liable', 'obligation', 'patent', 'penalty', 'provision', 'terminate',
  'trademark', 'warranty', 'indemnify', 'jurisdiction', 'waive', 'deed',
  'litigation', 'sanction', 'subcontract', 'disclosure', 'proprietary',
  'non-disclosure',
]);

export function getDifficulty(word: string): Difficulty {
  const w = word.toLowerCase();
  if (EASY_WORDS.has(w)) return 'easy';
  if (HARD_WORDS.has(w)) return 'hard';
  return 'medium';
}

/** 重複を除去して難易度でフィルタリングした単語プールを返す */
export function getByDifficulty(difficulty: Difficulty | 'all'): VocabItem[] {
  const unique = Array.from(
    new Map(TOEIC_WORDS.map((w) => [w.word.toLowerCase(), w])).values()
  );
  if (difficulty === 'all') return unique;
  return unique.filter((w) => getDifficulty(w.word) === difficulty);
}
